// Shared doctors database — used by both ReferredDoctors and /specialists page
export const ALL_DOCTORS = [
  {
    id: 1,
    name: 'Dr. Priya Sharma',
    spec: 'Cardiologist',
    hospital: 'Apollo Hospitals, Delhi',
    exp: '12 yrs',
    rating: '4.8',
    reviews: 234,
    distance: '2.4 km',
    phone: '+919876543210',
    available: true,
    availableSlot: 'Today, 4:30 PM',
    tags: ['Heart', 'Cardiology', 'Hypertension', 'ECG'],
  },
  {
    id: 2,
    name: 'Dr. Rajesh Verma',
    spec: 'General Physician',
    hospital: 'Primary Health Centre, Rohini',
    exp: '15 yrs',
    rating: '4.6',
    reviews: 410,
    distance: '1.2 km',
    phone: '+919876543211',
    available: true,
    availableSlot: 'Today, 3:00 PM',
    tags: ['General', 'Fever', 'Cold', 'Primary Care'],
  },
  {
    id: 3,
    name: 'Dr. Anita Desai',
    spec: 'Neurologist',
    hospital: 'NIMHANS, Bangalore',
    exp: '10 yrs',
    rating: '4.9',
    reviews: 189,
    distance: '5.1 km',
    phone: '+919876543212',
    available: false,
    availableSlot: 'Tomorrow, 10:00 AM',
    tags: ['Neurology', 'Headache', 'Seizure', 'Brain'],
  },
  {
    id: 4,
    name: 'Dr. Amit Patel',
    spec: 'Orthopedist',
    hospital: 'Kokilaben Hospital, Mumbai',
    exp: '8 yrs',
    rating: '4.5',
    reviews: 156,
    distance: '3.0 km',
    phone: '+919876543213',
    available: true,
    availableSlot: 'Today, 5:00 PM',
    tags: ['Orthopedics', 'Bone', 'Joint', 'Fracture', 'Spine'],
  },
  {
    id: 5,
    name: 'Dr. Sneha Reddy',
    spec: 'Dermatologist',
    hospital: 'Manipal Hospital, Hyderabad',
    exp: '6 yrs',
    rating: '4.7',
    reviews: 98,
    distance: '4.2 km',
    phone: '+919876543214',
    available: true,
    availableSlot: 'Today, 6:00 PM',
    tags: ['Skin', 'Dermatology', 'Rash', 'Allergy'],
  },
  {
    id: 6,
    name: 'Dr. Vikram Singh',
    spec: 'Pulmonologist',
    hospital: 'AIIMS, New Delhi',
    exp: '14 yrs',
    rating: '4.8',
    reviews: 312,
    distance: '1.8 km',
    phone: '+919876543215',
    available: true,
    availableSlot: 'Tomorrow, 9:00 AM',
    tags: ['Lung', 'Pulmonology', 'Asthma', 'Breathing', 'TB'],
  },
  {
    id: 7,
    name: 'Dr. Meera Nair',
    spec: 'Gynecologist',
    hospital: 'Fortis Hospital, Chennai',
    exp: '11 yrs',
    rating: '4.9',
    reviews: 275,
    distance: '3.5 km',
    phone: '+919876543216',
    available: true,
    availableSlot: 'Today, 2:00 PM',
    tags: ['Gynecology', 'Women Health', 'Obstetrics', 'Pregnancy'],
  },
  {
    id: 8,
    name: 'Dr. Suresh Kumar',
    spec: 'Gastroenterologist',
    hospital: 'Max Hospital, Gurgaon',
    exp: '9 yrs',
    rating: '4.6',
    reviews: 143,
    distance: '6.0 km',
    phone: '+919876543217',
    available: false,
    availableSlot: 'Tomorrow, 11:00 AM',
    tags: ['Gastro', 'Stomach', 'Liver', 'Digestion', 'GI'],
  },
  {
    id: 9,
    name: 'Dr. Kavita Joshi',
    spec: 'Pediatrician',
    hospital: 'Rainbow Children Hospital, Pune',
    exp: '13 yrs',
    rating: '4.9',
    reviews: 380,
    distance: '2.1 km',
    phone: '+919876543218',
    available: true,
    availableSlot: 'Today, 4:00 PM',
    tags: ['Child', 'Pediatrics', 'Infant', 'Vaccination', 'Fever'],
  },
  {
    id: 10,
    name: 'Dr. Arjun Mehta',
    spec: 'Psychiatrist',
    hospital: 'NIMHANS, Delhi',
    exp: '7 yrs',
    rating: '4.7',
    reviews: 88,
    distance: '4.8 km',
    phone: '+919876543219',
    available: true,
    availableSlot: 'Today, 7:00 PM',
    tags: ['Mental Health', 'Psychiatry', 'Anxiety', 'Depression'],
  },
];

/**
 * Filter doctors by specialization keyword.
 * Falls back to first 4 doctors if no match found.
 */
export function getDoctorsBySpec(specialization = '') {
  if (!specialization) return ALL_DOCTORS;
  const kw = specialization.toLowerCase();
  const matched = ALL_DOCTORS.filter(
    (d) =>
      d.spec.toLowerCase().includes(kw) ||
      d.tags.some((t) => t.toLowerCase().includes(kw))
  );
  return matched.length > 0 ? matched : ALL_DOCTORS.slice(0, 4);
}
